default_agent: tempobook
agents:
  tempoWhatsapp:
    name: tempoWhatsapp
    entrypoint: /Users/sol/Desktop/VIRTUS/Strands AI Whatsapp agent/agent.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/sol/Desktop/VIRTUS/Strands AI Whatsapp agent
    aws:
      execution_role: arn:aws:iam::980416031204:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-812a4e962b
      execution_role_auto_create: false
      account: '980416031204'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-980416031204-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: tempoWhatsapp-3qKciSDS7U
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:980416031204:runtime/tempoWhatsapp-3qKciSDS7U
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_AND_LTM
      memory_id: BaseKnowledge_Memory-My4vTrGyoP
      memory_arn: null
      memory_name: tempoWhatsapp_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  tempobook:
    name: tempobook
    entrypoint: /Users/sol/Desktop/VIRTUS/Strands AI Whatsapp agent/agent.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/sol/Desktop/VIRTUS/Strands AI Whatsapp agent
    aws:
      execution_role: arn:aws:iam::111363583174:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-a7c919e672
      execution_role_auto_create: false
      account: '111363583174'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-111363583174-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: tempobook-ZZ2WidGgEw
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:111363583174:runtime/tempobook-ZZ2WidGgEw
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: tempobook_mem-3mEWYtCF4a
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:111363583174:memory/tempobook_mem-3mEWYtCF4a
      memory_name: tempobook_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
